config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :requests do
    member do
      post :approve
    end
  end
  resources :offers do
    member do
      post :request, to: 'offers#request_offer'
    end
  end
  resources :cars
  resources :users

  root 'offers#index'

  resources :reports, only: [] do
    collection do
      get 'user_offers', to: 'reports#user_offers', as: 'user_offers'
      get 'popular_pickup', to: 'reports#popular_pickup', as: 'popular_pickup'
      get 'popular_dropoff', to: 'reports#popular_dropoff', as: 'popular_dropoff'
    end
  end

end

app/models/request.rb
class Request < ActiveRecord::Base
  self.primary_keys = :offer_datetime, :offer_car_license_plate_number, :requester_username, :request_datetime
  belongs_to :requester, class_name: :User, foreign_key: :requester_username
  belongs_to :offer, foreign_key: [:offer_datetime, :offer_car_license_plate_number]

  def self.get_request(offer_datetime, offer_car_license_plate_number, requester_username, request_datetime)
    sql = "SELECT * FROM requests WHERE offer_datetime='#{offer_datetime}' AND "\
      "requester_username='#{requester_username}' AND "\
      "offer_car_license_plate_number='#{offer_car_license_plate_number}' AND "\
      "request_datetime = '#{request_datetime}';"
    Request.find_by_sql(sql).first
  end

  def self.get_offer_requests(offer_datetime, offer_car_license_plate_number)
    sql = "SELECT * FROM requests WHERE offer_datetime='#{offer_datetime}' AND "\
      "offer_car_license_plate_number='#{offer_car_license_plate_number}';"
    Request.find_by_sql(sql)
  end

  def self.get_taken_offer_request(offer_datetime, offer_car_license_plate_number)
    sql = "SELECT * FROM requests WHERE offer_datetime='#{offer_datetime}' AND "\
      "offer_car_license_plate_number='#{offer_car_license_plate_number}' AND status = 1;"
    Request.find_by_sql(sql).first
  end


  def self.new_request(params)
    offer_car_license_plate_number = params[:offer_car_license_plate_number]
    offer_datetime = params[:offer_datetime]
    requester_username = params[:requester_username]
    request_datetime = params[:request_datetime]

    offer = Offer.get_offer(offer_datetime, offer_car_license_plate_number)
    return false unless offer.present?
    requester = User.get_user(requester_username)
    return false unless requester.present?

    sql = "INSERT INTO requests "\
      "(offer_car_license_plate_number, offer_datetime, requester_username, request_datetime) "\
      "VALUES ('#{offer_car_license_plate_number}', '#{offer_datetime}', '#{requester_username}', '#{request_datetime}');"
    ActiveRecord::Base.connection.execute sql

    [offer_datetime, offer_car_license_plate_number, requester_username, request_datetime]
  end

  def self.approve_request(offer_datetime, offer_car_license_plate_number, requester_username, request_datetime)
    offer = Offer.get_offer(offer_datetime, offer_car_license_plate_number)
    return false unless offer.present?
    requester = User.get_user(requester_username)
    return false unless requester.present?
    car = Car.get_car(offer.car_license_plate_number)
    owner = User.get_user(car.owner_username)

    sql1 = "UPDATE requests "\
      "SET status=1 "\
      "WHERE offer_datetime='#{offer_datetime}' AND "\
      "requester_username='#{requester_username}' AND "\
      "offer_car_license_plate_number='#{offer_car_license_plate_number}' AND "\
      "request_datetime = '#{request_datetime}';"
    ActiveRecord::Base.connection.execute sql1

    sql2 = "UPDATE users "\
      "SET credits = credits - #{offer.cost.to_i} "\
      "WHERE users.username='#{requester_username}';"
    ActiveRecord::Base.connection.execute sql2

    sql3 = "UPDATE users u SET credits = credits + #{offer.cost.to_i} "\
      "WHERE EXISTS (SELECT * FROM cars c INNER JOIN offers o ON o.car_license_plate_number = c.license_plate_number "\
      "WHERE c.owner_username = u.username AND c.license_plate_number = '#{offer.car_license_plate_number}');"
    ActiveRecord::Base.connection.execute sql3
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: [:show, :edit, :update, :destroy, :approve]

  # GET /requests/1
  # GET /requests/1.json
  def show
  end

  # POST /requests
  # POST /requests.json
  def create
    status = Request.new_request(request_params)
    @request = Request.get_request(status[0], status[1], status[2], status[3]) if status
    respond_to do |format|
      if status
        format.html { redirect_to @request, notice: 'Request was successfully created.' }
        format.json { render :show, status: :created, location: @request }
      else
        format.html { render :new }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  def approve
    User.transaction do
      Request.approve_request(@paramss[0], @paramss[1], @paramss[2], @paramss[3])
    end
    redirect_to offers_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @paramss= params[:id].split(',')
      @request = Request.get_request(@paramss[0], @paramss[1], @paramss[2], @paramss[3])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_params
      params[:requester_username] = current_user.username
      params[:request_datetime] = Time.now
      params.require(:request).permit(:status, :offer_datetime, :offer_car_license_plate_number, :requester_username, :request_datetime)
    end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_form.html.erb
<%= simple_form_for(@request) do |f| %>
  <% if @request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% @request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.input :status %>
  <%= f.input :offer_datetime %>
  <%= f.input :offer_car_license_plate_number %>
  <%= f.submit %>
<% end %>

app/views/requests/edit.html.erb
<h1>Editing Request</h1>

<%= render 'form' %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', :back %>

app/views/requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Requests</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Status</th>
      <th>Offer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @requests.each do |request| %>
      <tr>
        <td><%= request.requester.username %></td>
        <td><%= request.status %></td>
        <td><%= request.offer %></td>
        <td><%= link_to 'Show', request %></td>
        <td><%= link_to 'Edit', edit_request_path(request) %></td>
        <td><%= link_to 'Destroy', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Request', new_request_path %>

app/views/requests/new.html.erb
<h1>New Request</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @request.requester.username %>
</p>

<p>
  <strong>Status:</strong>
  <%= @request.status ? 'Approved' : 'Not Approved' %>
</p>

<p>
  <strong>Offer:</strong>
  <%= @request.offer.to_sym %>
</p>

<% if @request.offer.car.owner == current_user %>
<%= link_to 'Approve', approve_request_path(@request), method: :post %> |
<% end %>
<%= link_to 'Back', :back %>