config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :requests do
    member do
      post :approve
    end
  end
  resources :offers do
    member do
      post :request, to: 'offers#request_offer'
    end
  end
  resources :cars
  resources :users

  root 'offers#index'

  resources :reports, only: [] do
    collection do
      get 'user_offers', to: 'reports#user_offers', as: 'user_offers'
      get 'popular_pickup', to: 'reports#popular_pickup', as: 'popular_pickup'
      get 'popular_dropoff', to: 'reports#popular_dropoff', as: 'popular_dropoff'
    end
  end

end

app/models/offer.rb
class Offer < ActiveRecord::Base
  self.primary_keys = :datetime, :car_license_plate_number
  belongs_to :car, foreign_key: :car_license_plate_number
  has_many :requests, dependent: :destroy
  validates :datetime, presence: true
  validates :car_license_plate_number, presence: true
  validates :cost, presence: true
  validate :valid_number_of_vacancies

  def valid_number_of_vacancies
    return if vacancies.present? && vacancies > 0 && vacancies < car.seats
    errors.add(:vacancies, 'must be within the number of seats in the car')
  end

  def to_sym
    "Offer for car license number #{car_license_plate_number} on date #{datetime}"
  end

  def self.get_offer(datetime, car_license_plate_number)
    sql = "SELECT * FROM offers WHERE car_license_plate_number='#{car_license_plate_number} '"\
      "AND datetime='#{datetime}'"
    Offer.find_by_sql(sql).first
  end

  def self.get_all_offers
    sql = "SELECT * FROM offers"
    Offer.find_by_sql(sql)
  end

  def self.search_offers(keyword, pick_up_point, drop_off_point, vancancy_lower_limit, vancancy_upper_limit, cost_lower_limit, cost_upper_limit)
    sql = "SELECT * FROM offers WHERE "\
      "(car_license_plate_number LIKE '%#{keyword}%' "\
      "OR datetime LIKE '%#{keyword}%' "\
      "OR pickUpPoint LIKE '%#{keyword}%' "\
      "OR dropOffPoint LIKE '%#{keyword}%' "\
      "OR vacancies LIKE '%#{keyword}%' "\
      "OR cost LIKE '%#{keyword}%')"
    sql = sql + "AND pickUpPoint LIKE '%#{pick_up_point}%'"
    sql = sql + "AND dropOffPoint LIKE '%#{drop_off_point}%'"
    sql = sql + "AND vacancies >= '#{vancancy_lower_limit}'" if !vancancy_lower_limit.blank?
    sql = sql + "AND vacancies <= '#{vancancy_upper_limit}'" if !vancancy_upper_limit.blank?
    sql = sql + "AND cost >= '#{cost_lower_limit}'" if !cost_lower_limit.blank?
    sql = sql + "AND cost <= '#{cost_upper_limit}'" if !cost_upper_limit.blank?
    Offer.find_by_sql(sql)
  end

  def self.new_offer(params)
    car_license_plate_number = params[:car_license_plate_number]
    datetime = params["datetime(1i)"] + "-" + params["datetime(2i)"] + "-" + params["datetime(3i)"] + "-" + params["datetime(4i)"]+":"+params["datetime(5i)"]
    pickUpPoint = params[:pickUpPoint]
    dropOffPoint = params[:dropOffPoint]
    vacancies = params[:vacancies].to_i
    cost = params[:cost].to_i

    car = Car.get_car(car_license_plate_number)
    return false unless datetime.present? && car_license_plate_number.present?
    return false unless car.present?
    return false unless vacancies.present? && vacancies > 0 && vacancies < car.seats
    return false if cost.blank? || cost < 0

    sql = "INSERT INTO offers "\
      "(car_license_plate_number, datetime, pickUpPoint, dropOffPoint, vacancies, cost) "\
      "VALUES ('#{car_license_plate_number}', '#{datetime}', '#{pickUpPoint}', '#{dropOffPoint}', '#{vacancies}', '#{cost}');"
    ActiveRecord::Base.connection.execute sql

    [datetime, car_license_plate_number]
  end

  def self.update_offer(params, datetime, car_license_plate_number)
    pickUpPoint = params[:pickUpPoint]
    dropOffPoint = params[:dropOffPoint]
    vacancies = params[:vacancies].to_i
    cost = params[:cost].to_i

    car = Car.get_car(car_license_plate_number)
    return false unless datetime.present? && car_license_plate_number.present?
    return false unless car.present?
    return false unless vacancies.present? && vacancies > 0 && vacancies < car.seats
    return false if cost.blank? || cost < 0

    sql = "UPDATE offers "\
      "SET pickUpPoint='#{pickUpPoint}', dropOffPoint='#{dropOffPoint}', "\
      "vacancies='#{vacancies}', cost='#{cost}' "\
      "WHERE datetime='#{datetime}' AND car_license_plate_number='#{car_license_plate_number}';"

    ActiveRecord::Base.connection.execute sql
    true
  end

  def self.destroy_offer(datetime, car_license_plate_number)
    sql = "DELETE FROM offers "\
      "WHERE datetime='#{datetime}' AND car_license_plate_number='#{car_license_plate_number}';"
    ActiveRecord::Base.connection.execute sql
    true
  end

  def self.popular_pickup_points
    sql = 'SELECT o.pickUpPoint, COUNT(DISTINCT o.datetime, o.car_license_plate_number) AS num_offers, ' \
      'COUNT(DISTINCT r.offer_datetime, r.offer_car_license_plate_number, r.requester_username, r.request_datetime) AS num_requests '\
      'FROM offers o LEFT JOIN requests r ON r.offer_datetime = o.datetime AND '\
      'r.offer_car_license_plate_number = o.car_license_plate_number '\
      'GROUP BY o.pickUpPoint ORDER BY num_offers, num_requests DESC'
    ActiveRecord::Base.connection.execute(sql).each
  end

  def self.popular_dropoff_points
    sql = 'SELECT o.dropOffPoint, COUNT(DISTINCT o.datetime, o.car_license_plate_number) AS num_offers, ' \
      'COUNT(DISTINCT r.offer_datetime, r.offer_car_license_plate_number, r.requester_username, r.request_datetime) AS num_requests '\
      'FROM offers o LEFT JOIN requests r ON r.offer_datetime = o.datetime AND '\
      'r.offer_car_license_plate_number = o.car_license_plate_number '\
      'GROUP BY dropOffPoint ORDER BY num_offers, num_requests DESC'
    ActiveRecord::Base.connection.execute(sql).each
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_offer, only: [:show, :edit, :update, :destroy, :request_offer]

  # GET /offers
  # GET /offers.json
  def index
    @offers = Offer.search_offers(params[:keyword],
      params[:pick_up_point], params[:drop_off_point],
      params[:vancancy_lower_limit], params[:vancancy_upper_limit],
      params[:cost_lower_limit], params[:cost_upper_limit])
  end

  # GET /offers/1
  # GET /offers/1.json
  def show
  end

  # GET /offers/new
  def new
    @offer = Offer.new
  end

  # GET /offers/1/edit
  def edit
  end

  # POST /offers
  # POST /offers.json
  def create
    ids = Offer.new_offer(offer_params)
    @offer = Offer.get_offer(ids[0], ids[1]) if ids
    #HACK
    @offer = Offer.create(offer_params) unless ids
    respond_to do |format|
      if ids
        format.html { redirect_to @offer, notice: 'Offer was successfully created.' }
        format.json { render :show, status: :created, location: @offer }
      else
        format.html { render :new }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offers/1
  # PATCH/PUT /offers/1.json
  def update
    ids = Offer.update_offer(offer_params, @paramss[0], @paramss[1])
    @offer.update(offer_params) unless ids
    respond_to do |format|
      if ids
        format.html { redirect_to @offer, notice: 'Offer was successfully updated.' }
        format.json { render :show, status: :ok, location: @offer }
      else
        format.html { render :edit }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1
  # DELETE /offers/1.json
  def destroy
    Offer.destroy_offer(@paramss[0], @paramss[1])
    respond_to do |format|
      format.html { redirect_to offers_url, notice: 'Offer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def request_offer
    @request = Request.new
    @request.requester_username = current_user.username
    @request.offer_datetime = @offer.datetime
    @request.offer_car_license_plate_number = @offer.car_license_plate_number
    @request.request_datetime = Time.now
    @request.save
    respond_to :js
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offer
      @paramss = params[:id].split(',')
      @offer = Offer.get_offer(@paramss[0], @paramss[1])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def offer_params
      params.require(:offer).permit(:datetime,
                                    :pickUpPoint, :dropOffPoint, :vacancies, :car_license_plate_number, :cost)
    end
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/offers/_form.html.erb
<%= simple_form_for(@offer) do |f| %>
  <% if @offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@offer.errors.count, "error") %> prohibited this offer from being saved:</h2>

      <ul>
      <% @offer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% if @offer.new_record? %>
    <%= f.input :datetime %>
  <% end %>
  <%= f.input :pickUpPoint %>
  <%= f.input :dropOffPoint %>
  <%= f.input :cost %>
  <%= f.input :vacancies %>
  <% if @offer.new_record? %>
    <%= f.association :car, collection: Car.where(owner_username: current_user.username) %>
  <% end %>
  <%= f.submit %>
<% end %>

app/views/offers/_request.html.erb
<% request_show = "Request by #{request.requester.username} at #{request.request_datetime}" %>
<li><%= link_to request_show, request_path(request) %></li>

app/views/offers/edit.html.erb
<h1>Editing Offer</h1>

<%= render 'form' %>

<%= link_to 'Show', @offer %> |
<%= link_to 'Back', :back %>

app/views/offers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Offers</h1>

<%= form_tag offers_path, :method => 'get' do %>
  <p>
    <%= label_tag(:keyword, "Keyword:") %>
    <%= text_field_tag :keyword, params[:keyword], size: 25 %>  
  </p>
  <p>
    <%= label_tag(:pick_up_point, "Pick up point:") %>
    <%= text_field_tag :pick_up_point, params[:pick_up_point], size: 21 %>
  </p>
  <p>
    <%= label_tag(:drop_off_point, "Drop off point:") %>
    <%= text_field_tag :drop_off_point, params[:drop_off_point], size: 20 %>  
  </p>
  <p>
    <%= label_tag(:vancancy_lower_limit, "Vancancies:") %>
    <%= text_field_tag :vancancy_lower_limit, params[:vancancy_lower_limit], size: 5 %>
    <%= label_tag(:vancancy_upper_limit, "  -  ") %>
    <%= text_field_tag :vancancy_upper_limit, params[:vancancy_upper_limit], size: 5 %>  
  </p>
  <p>
    <%= label_tag(:cost_lower_limit, "Cost:") %>
    <%= text_field_tag :cost_lower_limit, params[:cost_lower_limit], size: 5 %>
    <%= label_tag(:cost_upper_limit, "  -  ") %>
    <%= text_field_tag :cost_upper_limit, params[:cost_upper_limit], size: 5 %>  
  </p>
  <%= submit_tag "Search", :name => nil %>
<% end %>

<table class="table table-striped datatable">
  <thead>
    <tr>
      <th>Datetime</th>
      <th>Pick up point</th>
      <th>Drop off point</th>
      <th>Vacancies</th>
      <th>Cost</th>
      <th>Car</th>
      <th>Requests</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @offers.each do |offer| %>
      <tr>
        <td><%= offer.datetime %></td>
        <td><%= offer.pickUpPoint %></td>
        <td><%= offer.dropOffPoint %></td>
        <td><%= offer.vacancies %></td>
        <td><%= offer.cost %></td>
        <td><%= link_to offer.car.name, car_path(offer.car) %></td>
        <% requests = Request.get_offer_requests(offer.datetime, offer.car_license_plate_number) %>
        <% offer_taken = Request.get_taken_offer_request(offer.datetime, offer.car_license_plate_number) %>
        <% if offer_taken.present? %>
            <td>Taken by <%= offer_taken.requester.username %></td>
        <% else %>
            <td id="<%= offer.hash %>">
                <% requests.each do |request| %>
                    <%= render partial: 'offers/request', locals: { request: request } %>
                <% end %>
                <li><%= link_to 'Request now', request_offer_path(offer), remote: true, method: :post %></li>
            </td>
        <% end %>
        <% if offer.car.owner == current_user %>
            <td><%= link_to 'Edit', edit_offer_path(offer) %></td>
            <td><%= link_to 'Destroy', offer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Offer', new_offer_path %>

app/views/offers/new.html.erb
<h1>New Offer</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/offers/request_offer.js.erb
$('td#<%= @request.offer.hash %>').prepend('<%= j(render partial: "offers/request", locals: { request: @request } ) %>');

app/views/offers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Datetime:</strong>
  <%= @offer.datetime %>
</p>

<p>
  <strong>Pickuppoint:</strong>
  <%= @offer.pickUpPoint %>
</p>

<p>
  <strong>Dropoffpoint:</strong>
  <%= @offer.dropOffPoint %>
</p>

<p>
  <strong>Vacancies:</strong>
  <%= @offer.vacancies %>
</p>

<p>
  <strong>Car:</strong>
  <%= @offer.car.name %>
</p>

<%= link_to 'Edit', edit_offer_path(@offer) %> |
<%= link_to 'Back', :back %>