config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :requests do
    member do
      post :approve
    end
  end
  resources :offers do
    member do
      post :request, to: 'offers#request_offer'
    end
  end
  resources :cars
  resources :users

  root 'offers#index'

  resources :reports, only: [] do
    collection do
      get 'user_offers', to: 'reports#user_offers', as: 'user_offers'
      get 'popular_pickup', to: 'reports#popular_pickup', as: 'popular_pickup'
      get 'popular_dropoff', to: 'reports#popular_dropoff', as: 'popular_dropoff'
    end
  end

end

app/models/car.rb
class Car < ActiveRecord::Base
  self.primary_key = 'license_plate_number'
  belongs_to :owner, class_name: :User, foreign_key: :owner_username
  has_many :offers, dependent: :destroy
  validate :at_least_one_seat
  validates :license_plate_number, presence: true

  def at_least_one_seat
    return if seats.present? && seats > 0
    errors.add(:seats, 'must have at least one seat')
  end

  def self.get_car(license_plate_number)
    sql = "SELECT * FROM cars WHERE license_plate_number='#{license_plate_number}'"
    Car.find_by_sql(sql).first
  end

  def self.get_all_cars
    sql = "SELECT * FROM cars"
    Car.find_by_sql(sql)
  end

  def self.search_all_cars(keyword, seats_lower_limit, seats_upper_limit)
    sql = "SELECT * FROM cars WHERE "\
      "(license_plate_number LIKE '%#{keyword}%'"\
      "OR name LIKE '%#{keyword}%'"\
      "OR owner_username LIKE '%#{keyword}%')"
    sql = sql + "AND seats >= '#{seats_lower_limit}'" if !seats_lower_limit.blank?
    sql = sql + "AND seats <= '#{seats_upper_limit}'" if !seats_upper_limit.blank?
    Car.find_by_sql(sql)
  end

  def self.get_user_cars(username)
    sql = "SELECT * FROM cars WHERE owner_username='#{username}'"
    Car.find_by_sql(sql)
  end

  def self.search_user_cars(username, keyword)
    sql = "SELECT * FROM cars WHERE owner_username='#{username}'"\
      "AND (license_plate_number LIKE '%#{keyword}%'"\
      "OR name LIKE '%#{keyword}%'"\
      "OR seats LIKE '%#{keyword}%')"
    Car.find_by_sql(sql)
  end

  def self.new_car(params)
    name = params[:name]
    license_plate_number = params[:license_plate_number]
    owner_username = params[:owner_username]
    seats = params[:seats].to_i

    return false if seats.blank? || seats <= 0 || license_plate_number.blank?

    sql = "INSERT INTO cars "\
      "(owner_username, name, license_plate_number, seats) "\
      "VALUES ('#{owner_username}', '#{name}', '#{license_plate_number}', '#{seats}');"
    ActiveRecord::Base.connection.execute sql

    license_plate_number
  end

  def self.update_car(params, license_plate_number)
    name = params[:name]
    seats = params[:seats].to_i

    return false if seats <= 0

    sql = "UPDATE cars "\
      "SET name='#{name}', seats='#{seats}' "\
      "WHERE license_plate_number='#{license_plate_number}';"

    ActiveRecord::Base.connection.execute sql
    true
  end

  def self.destroy_car(license_plate_number)
    sql = "DELETE FROM cars "\
      "WHERE license_plate_number='#{license_plate_number}';"
    ActiveRecord::Base.connection.execute sql
    true
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    if current_user.isAdmin?
      @cars = Car.search_all_cars(params[:keyword], params[:seats_lower_limit], params[:seats_upper_limit])
    else
      @cars = Car.search_user_cars(current_user.username, params[:keyword], params[:seats_lower_limit], params[:seats_upper_limit])
    end
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    new_car = Car.new_car(car_params)
    car = Car.get_car(new_car)
    # HACK
    @car = Car.create(car_params) unless new_car
    respond_to do |format|
      if new_car
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    update_car = Car.update_car(car_params, params[:id])
    # HACK
    @car.update(car_params) unless update_car
    respond_to do |format|
      if update_car
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    Car.destroy_car(params[:id])
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.get_car(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params[:car][:owner_username] = current_user.username
      params.require(:car).permit(:name, :seats, :owner_username, :license_plate_number)
    end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.erb
<%= simple_form_for(@car) do |f| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% @car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% if @car.new_record? %>
    <%= f.input :license_plate_number %>
  <% end %>
  <%= f.input :name %>
  <%= f.input :seats %>
  <%= f.submit %>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form' %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', :back %>

app/views/cars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cars</h1>

<%= form_tag cars_path, :method => 'get' do %>
  <p>
    <%= label_tag(:keyword, "Keyword:") %>
    <%= text_field_tag :keyword, params[:keyword], size: 20 %>  
  </p>
  <p>
    <%= label_tag(:seats_lower_limit, "Seats:") %>
    <%= text_field_tag :seats_lower_limit, params[:seats_lower_limit], size: 5 %>
    <%= label_tag(:seats_upper_limit, "  -  ") %>
    <%= text_field_tag :seats_upper_limit, params[:seats_upper_limit], size: 5 %>  
  </p>
  <%= submit_tag "Search", :name => nil %>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>License Plate Number</th>
      <th>Name</th>
      <th>Seats</th>
      <th>Owned by</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.license_plate_number %></td>
        <td><%= car.name %></td>
        <td><%= car.seats %></td>
        <td><%= link_to car.owner.username, user_path(car.owner.username) %></td>
        <% if current_user.isAdmin || current_user == car.owner %>
        <td><%= link_to 'Edit', edit_car_path(car) %></td>
        <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Car', new_car_path %>

app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @car.name %>
</p>

<p>
  <strong>Seats:</strong>
  <%= @car.seats %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @car.owner.username %>
</p>

<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', :back %>