config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :requests do
    member do
      post :approve
    end
  end
  resources :offers do
    member do
      post :request, to: 'offers#request_offer'
    end
  end
  resources :cars
  resources :users

  root 'offers#index'

  resources :reports, only: [] do
    collection do
      get 'user_offers', to: 'reports#user_offers', as: 'user_offers'
      get 'popular_pickup', to: 'reports#popular_pickup', as: 'popular_pickup'
      get 'popular_dropoff', to: 'reports#popular_dropoff', as: 'popular_dropoff'
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cs2102carpooling</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.5/journal/bootstrap.min.css" rel="stylesheet" integrity="sha256-bPSyJP9+ovy9/YbIwvZyX6r2M4PkiF01vt0zuDLUEzs= sha512-F4ep7hh9V7i7UvRF56Vq8VgjFIFGRVaE2y5UZ2FtIcMWoLFiDxTmHgnDm1XDZGcc6Vtp+kwtL0Kd3VA8uBMK9g==" crossorigin="anonymous">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="//cdn.datatables.net/1.10.9/js/jquery.dataTables.min.js" %></script>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
    <% if current_user %>
    <nav class="panel navbar navbar-default">
        <div class="container-fluid">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <a class="navbar-brand" href="/">Carpooling</a>
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li>
                <%= link_to 'Users', users_path %>
              </li>
              <li>
                <%= link_to 'Cars', cars_path %>
              </li>
              <li>
                <%= link_to 'Offers', offers_path %>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Reports <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to 'User Car Sharing Statistics', user_offers_reports_path %></li>
                  <li><%= link_to 'Popular Pickup Points', popular_pickup_reports_path %></li>
                  <li><%= link_to 'Popular Dropoff Points', popular_dropoff_reports_path %></li>
                </ul>
              </li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
              <li>
                <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
      </nav>
    <% end %>

    <div class="panel">
      <div class="panel-body">
        <%= yield %>
      </div>
    </div>
</div>
</body>
</html>